apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
  namespace: collabcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
    spec:
      containers:
        - name: execution-service
          image: collabcode/execution-service:latest
          ports:
            - containerPort: 4001
